// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQKwnghqa6JAqrntyrSup5kaF5dvf1N2E',
    appId: '1:745719121683:web:1671306045c3dd840fbce6',
    messagingSenderId: '745719121683',
    projectId: 'apollo-my-restaurant-app',
    authDomain: 'apollo-my-restaurant-app.firebaseapp.com',
    storageBucket: 'apollo-my-restaurant-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCexA6bcCA9Qytk76AxMdC85YV4swsOZCU',
    appId: '1:745719121683:android:e8ead58d78e3a9890fbce6',
    messagingSenderId: '745719121683',
    projectId: 'apollo-my-restaurant-app',
    storageBucket: 'apollo-my-restaurant-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-zl0AIGlFgFjRMyNlrqM6Dl5j8J0rUcM',
    appId: '1:745719121683:ios:ec8c2188db4f5e4d0fbce6',
    messagingSenderId: '745719121683',
    projectId: 'apollo-my-restaurant-app',
    storageBucket: 'apollo-my-restaurant-app.firebasestorage.app',
    iosBundleId: 'com.example.myResturant',
  );
}
